# Generated by Django 2.1.7 on 2019-04-02 01:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amenities', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Amenities',
                'verbose_name_plural': 'Amenities',
            },
        ),
        migrations.CreateModel(
            name='BoatSpec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.IntegerField()),
                ('capacity', models.IntegerField()),
                ('boat_description', models.TextField(max_length=250)),
            ],
            options={
                'verbose_name': 'Boat Specification',
                'verbose_name_plural': 'Boat Specifications',
            },
        ),
        migrations.CreateModel(
            name='FishingTechnique',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technique', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Fishing Technique',
                'verbose_name_plural': 'Fishing Techniques',
            },
        ),
        migrations.CreateModel(
            name='FishingType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Fishing Type',
                'verbose_name_plural': 'Fishing Types',
            },
        ),
        migrations.CreateModel(
            name='GuideBusiness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_city', models.CharField(max_length=150)),
                ('location_state', models.CharField(max_length=50)),
                ('business_description', models.TextField(max_length=1500)),
                ('amenities', models.ManyToManyField(to='guides.Amenities')),
                ('boat_spec', models.ManyToManyField(to='guides.BoatSpec')),
                ('fishing_technique', models.ManyToManyField(to='guides.FishingTechnique')),
                ('fishing_type', models.ManyToManyField(to='guides.FishingType')),
            ],
            options={
                'verbose_name_plural': 'Guide Businesses',
            },
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_title', models.CharField(max_length=50)),
                ('policy_description', models.TextField(max_length=250)),
            ],
            options={
                'verbose_name': 'Policy',
                'verbose_name_plural': 'Policies',
            },
        ),
        migrations.CreateModel(
            name='ServiceLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Service Location',
                'verbose_name_plural': 'Service Locations',
            },
        ),
        migrations.CreateModel(
            name='TripeInclude',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('includes', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Trip Includes',
                'verbose_name_plural': 'Trip Includes',
            },
        ),
        migrations.CreateModel(
            name='WaterTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water_type', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Water Type',
                'verbose_name_plural': 'Water Types',
            },
        ),
        migrations.AddField(
            model_name='servicelocation',
            name='water_type',
            field=models.ManyToManyField(to='guides.WaterTypes'),
        ),
        migrations.AddField(
            model_name='guidebusiness',
            name='policy',
            field=models.ManyToManyField(to='guides.Policy'),
        ),
        migrations.AddField(
            model_name='guidebusiness',
            name='service_location',
            field=models.ManyToManyField(to='guides.ServiceLocation'),
        ),
        migrations.AddField(
            model_name='guidebusiness',
            name='trip_includes',
            field=models.ManyToManyField(to='guides.TripeInclude'),
        ),
        migrations.AddField(
            model_name='guidebusiness',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
