# Generated by Django 2.1.7 on 2019-04-06 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0002_trip'),
    ]

    operations = [
        migrations.AddField(
            model_name='guidebusiness',
            name='trip_package',
            field=models.ManyToManyField(to='guides.Trip'),
        ),
    ]
